base_url = "https://www.stanistan.com"
title = "stanistan"

compile_sass = true
build_search_index = false
generate_feed = true
feed_filename = "rss.xml"
taxonomies = []

[markdown]
highlight_code = true
highlight_theme = "inspired-github"
external_links_no_follow = true
external_links_no_referrer = true
extra_syntaxes_and_themes = [ "./themes" ]

[extra]
repo_content_path = "stanistan/stanistan.github.io/the-details/content"
show_tags = false # now tags taxonomy just yet

[extra.invoice]
enabled = false
host = "http://localhost:3000"

[extra.debug]
templates = false
css = true
